In [1]:
# keyword 'with' is used to end the file automatically
# Accessing text file

with open("text1") as practicefile:
    contents = practicefile.read()
    print(contents)

123
456
789





In [2]:
# removing white or extra spaces

with open("text1") as practicefile:
    contents = practicefile.read()
    print(contents.rstrip())

123
456
789


In [3]:
# Accesing folder with text files

with open("Untitled Folder/text2") as practicefile:
    contents = practicefile.read()
    print(contents.rstrip())

zain
manzar
osama
ammar


In [4]:
# Accessing folder and file by uisng file path

filePath = "Untitled Folder/text2"
with open(filePath) as practicefile:
    contents = practicefile.read()
    print(contents.rstrip())

zain
manzar
osama
ammar


In [5]:
# getting file outside the scope of 'with' with help of for loop
# Empty spaces after every line automatically

filePath = "text1"
with open(filePath) as practicefile:
    contents = practicefile.readlines()

for line in contents:
    print(line)

123

456

789







In [6]:
# Now rstrip only remove that spaces which are not in textfile

filePath = "text1"
with open(filePath) as practicefile:
    contents = practicefile.readlines()

for line in contents:
    print(line.rstrip())

123
456
789




In [7]:
# Print textfile Data in single line

filePath = "text1"
with open(filePath) as practicefile:
    contents = practicefile.readlines()
    
oneline = ""

for line in contents:
    oneline += line.rstrip()
    
print(oneline)

123456789


In [8]:
# slicing

filePath = "text1"
with open(filePath) as practicefile:
    contents = practicefile.readlines()
    
oneline = ""

for line in contents:
    oneline += line.rstrip()
    
print(oneline[:6] + " " + "still continue")

123456 still continue


In [9]:
# In this example slicing will not change the actual length

filePath = "text1"
with open(filePath) as practicefile:
    contents = practicefile.readlines()
    
oneline = ""

for line in contents:
    oneline += line.rstrip()
    
print(oneline[:6] + " " + "still continue")
print(len(oneline))

123456 still continue
9


In [10]:
# if we want to perform write operation then we have to use 'w' 

filePath = "text1"

with open(filePath , "w") as practiceFile:
    practiceFile.write("000")
    
# it will change only textfile
# it will remove all data in textfile and it will show 000 (given data here)

In [11]:
# concatinate two commands in textfile in one line

filePath = "text1"

with open(filePath , "w") as practiceFile:
    practiceFile.write("000")
    practiceFile.write("111")

In [12]:
# concatinate two commands in textfile in next line (using \n)

filePath = "text1"

with open(filePath , "w") as practiceFile:
    practiceFile.write("000 \n")
    practiceFile.write("111")

In [16]:
# don't delte previous content and new content will add them (by using a) in textfile

filePath = "text1"

with open(filePath , "a") as practiceFile: # operation change w --> a
    practiceFile.write("222") # method same e.g, write

In [17]:
# else will run because second_num is non-zero

first_num = 5
second_num = 3

try:
    answer = first_num / second_num
    
except ZeroDivisionError:
    print("This operation can not be performed")
    
else:
    print(answer)

1.6666666666666667


In [18]:
# Controlling divsion by '0' Error

first_num = 5
second_num = 0

try:
    answer = first_num / second_num
    
except ZeroDivisionError:
    print("This operation can not be performed")
    
else:
    print(answer)

This operation can not be performed


In [19]:
# else statement will because given File Path is Correct

try:
    with open("text1") as practiceFile:
        contents = practiceFile.read()
        
except FileNotFoundError:
    print("Your File Path is not Correct")
    
else:
    print(contents)

000 
111222


In [20]:
# Controlling File not found Error

try:
    with open("text3") as practiceFile:
        contents = practiceFile.read()
        
except FileNotFoundError:
    print("Your File Path is not Correct")
    
else:
    print(contents)

Your File Path is not Correct


In [22]:
# Getting Data from Excel file

import csv

with open("history.csv") as practiceFile:
    contents = csv.reader(practiceFile)
    for line in contents:
        print(line)

['Programming Language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido va Russum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [23]:
# Math module import

import math
print(math.pi)

3.141592653589793


In [25]:
# giving desired name of module

import math as manzar
print(manzar.pi)

3.141592653589793


In [26]:
# without giving module name

from math import *
print(pi)

3.141592653589793


In [27]:
# ceil gives next possible number

import math
print(math.ceil(5.7))

6


In [28]:
# floor gives previous possible number

import math
print(math.floor(5.7))

5


In [1]:
# we use this command "pip install import_ipynb" on terminal of jupyter
# Just call any function from any file

import import_ipynb

import Untitled3

Untitled3.add(1,9)

importing Jupyter notebook from Untitled3.ipynb


10

In [38]:
# numpy

import numpy as np

data = np.random.randn(2,3)
print(data, '\n')
print(data + data, '\n')
print(data * 10 , '\n')
print(data.shape, '\n')
print(data.dtype, '\n')
print(data.ndim, '\n')

[[ 0.32760392  0.34322557  1.73197523]
 [-0.01154361 -0.59822229 -1.18380085]] 

[[ 0.65520784  0.68645114  3.46395046]
 [-0.02308721 -1.19644459 -2.36760169]] 

[[  3.27603921   3.4322557   17.31975228]
 [ -0.11543607  -5.98222293 -11.83800845]] 

(2, 3) 

float64 

2 



In [39]:
# generating 'zero' array through numpy

print(np.zeros(10), '\n')
print(np.zeros((3,6)), '\n')
print(np.zeros((2,3,6)), '\n')
print(np.empty((3,6)), '\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [40]:
# converting simple array into numpy array and changing type of array

arr = np.array([1, 2, 3, 4, 5])
print(arr.astype(np.float64))

[1. 2. 3. 4. 5.]


In [41]:
# diiferent operations on numpy array

arr = np.array([4, 2, 6, 8] , dtype = "int64")
print(arr * 2, '\n')
print(arr * arr, '\n')
print(2 / arr, '\n')
print(arr ** 2, '\n')
print(np.sqrt(arr), '\n')
print(np.exp(arr), '\n')
print(np.mean(arr), '\n')
print(np.sum(arr), '\n')
print(np.cumsum(arr), '\n')
print(np.sort(arr), '\n')

[ 8  4 12 16] 

[16  4 36 64] 

[0.5        1.         0.33333333 0.25      ] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

20 

[ 4  6 12 20] 

[2 4 6 8] 



In [42]:
# Boolean operations on numpy

arr = np.array([4, 2, 6, 8] , dtype = "int64")
print(arr * 2, '\n')
print(arr * arr, '\n')
print(2 / arr, '\n')
print(arr ** 2, '\n')
print(np.sqrt(arr), '\n')
print(np.exp(arr), '\n')
print(np.mean(arr), '\n')
print(np.sum(arr), '\n')
print(np.cumsum(arr), '\n')
print(np.sort(arr), '\n')

arr2 = np.array([0,1,3,5])

print(arr > arr2)

[ 8  4 12 16] 

[16  4 36 64] 

[0.5        1.         0.33333333 0.25      ] 

[16  4 36 64] 

[2.         1.41421356 2.44948974 2.82842712] 

[  54.59815003    7.3890561   403.42879349 2980.95798704] 

5.0 

20 

[ 4  6 12 20] 

[2 4 6 8] 

[ True  True  True  True]


In [43]:
# arange function and slicing in numpy

arr = np.arange(10)
print(arr)

arr2 = arr[5:8]
print(arr2)

arr[:3] = 0 # changing all slices value into 0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [44]:
# more features of numpy

namesArr = np.array(["Manzar", "Zain", "Ammar", "Osama", "Manzar"])

numArr = np.random.randn(5,3)

print(numArr, '\n')
print(namesArr, '\n')
print(namesArr ==  "Manzar", '\n')
print(numArr[namesArr == "Manzar"], '\n')
print(numArr[~(namesArr == "Manzar")], '\n')

print(np.unique(namesArr)) # sorting and duplicate remove

[[-0.97402261  0.55474452 -0.79013516]
 [-1.05217581 -1.32803566  0.54712315]
 [-0.81190987 -0.90253204 -1.04754929]
 [-0.6584087  -0.97859245  1.59666312]
 [ 0.06996008  0.46057161 -1.4659863 ]] 

['Manzar' 'Zain' 'Ammar' 'Osama' 'Manzar'] 

[ True False False False  True] 

[[-0.97402261  0.55474452 -0.79013516]
 [ 0.06996008  0.46057161 -1.4659863 ]] 

[[-1.05217581 -1.32803566  0.54712315]
 [-0.81190987 -0.90253204 -1.04754929]
 [-0.6584087  -0.97859245  1.59666312]] 

['Ammar' 'Manzar' 'Osama' 'Zain']


In [45]:
# functionality in numpy

arr = np.random.randn(4)
print(arr , '\n')

arr2 = np.random.randn(4)
print(arr , '\n')

print(np.maximum(arr,arr2), '\n')
print(np.minimum(arr,arr2), '\n')

[ 0.83514422 -0.48295627 -2.38021897  0.14395678] 

[ 0.83514422 -0.48295627 -2.38021897  0.14395678] 

[ 0.83514422 -0.48295627 -0.16541325  0.14395678] 

[ 0.20951316 -0.57141806 -2.38021897 -0.21822376] 

